vocab_list = [
    ("배우다", 0, None, "öyrənmək", 0),
    ("한국어", 0, None, "Koreya dili", 0),
    ("재미있다", 0, None, "maraqlı, əyləncəli", 0),
    ("먹다", 0, None, "yemək", 0),
    ("밥", 0, None, "düyü/yemək", 0),
    ("중국어", 0, None, "Çin dili", 0),
    ("영화", 0, None, "film", 0),
    ("음악", 0, None, "musiqi", 0),
    ("듣다", 0, None, "dinləmək", 0),
    ("읽다", 0, None, "oxumaq (kitab, qəzet və s.)", 0),
    ("버스", 0, None, "avtobus", 0),
    ("타다", 0, None, "minmək (버스를 타다)", 0),
    ("재미없다", 0, None, "maraqsız", 0),
    ("크다", 0, None, "böyük", 0),
    ("작다", 0, None, "balaca", 0),
    ("넓다", 0, None, "geniş", 0),
    ("좁다", 0, None, "dar", 0),
    ("많다", 0, None, "çox", 0),
    ("적다", 0, None, "az", 0),
    ("쉽다", 0, None, "asan", 0),
    ("어렵다", 0, None, "çətin", 0),
    ("공원", 0, None, "park", 0),
    ("깨끗하다", 0, None, "təmiz", 0),
    ("더럽다", 0, None, "çirkli", 0),
    ("잡지", 0, None, "jurnal", 0),
    ("커피", 0, None, "kofe", 0),
    ("마시다", 0, None, "içmək", 0),
    ("편지", 0, None, "məktub", 0),
    ("쓰다", 0, None, "yazmaq/istifadə etmək/acılı", 0),
    ("우유", 0, None, "süd", 0),
    ("노래", 0, None, "mahnı", 0),
    ("부르다", 0, None, "oxumaq(mahnı)/ çağırmaq (kimisə)", 0),
    ("춤", 0, None, "rəqs", 0),
    ("추다", 0, None, "etmək(rəqs)", 0),
    ("지하철", 0, None, "metro", 0),
    ("라디오", 0, None, "radio", 0),
    ("빵", 0, None, "çörək", 0),
    ("선물", 0, None, "hədiyyə", 0),
    ("주다", 0, None, "vermək", 0),
    ("사다", 0, None, "almaq", 0),
    ("가다", 0, None, "getmək", 0),
    ("층", 0, None, "mərtəbə", 0),
    ("호", 0, None, "nömrə (otaq, mənzil və s.)", 0),
    ("다니다", 0, None, "gedib-gəlmək", 0),
    ("가게", 0, None, "mağaza", 0),
    ("편의점", 0, None, "24 saat işləyən mağaza", 0),
    ("회사", 0, None, "şirkət", 0),
    ("대학교", 0, None, "universitet", 0),
    ("번", 0, None, "nömrəli", 0),
    ("전화번호", 0, None, "telefon nömrəsi", 0),
    ("빌딩", 0, None, "bina", 0),
    ("약국", 0, None, "aptek", 0),
    ("꽃집", 0, None, "gül mağazası", 0),
    ("기다리다", 0, None, "gözləmək", 0),
    ("지금", 0, None, "indi", 0),
    ("사무실", 0, None, "ofis", 0),
    ("친절하다", 0, None, "mehriban", 0),
    ("똑똑하다", 0, None, "ağıllı", 0),
    ("열심히", 0, None, "səylə, həvəslə", 0),
    ("수업", 0, None, "dərs", 0),
    ("끝나다", 0, None, "bitmək", 0),
    ("그리고", 0, None, "və", 0),
    ("매우", 0, None, "çox", 0),
    ("즐겁다", 0, None, "zövq almaq/əyləncəli", 0),
    ("초등학교", 0, None, "ibtidai sinif", 0),
    ("중학교", 0, None, "orta məktəb (5-8ci sinif)", 0),
    ("고등학교", 0, None, "orta məktəb (9-11ci sinif)", 0),
    ("년", 0, None, "il", 0),
    ("좋다", 0, None, "yaxşı", 0),
    ("나쁘다", 0, None, "pis", 0),
    ("빠르다", 0, None, "sürətli", 0),
    ("느리다", 0, None, "yavaş", 0),
    ("높다", 0, None, "yüksək", 0),
    ("낮다", 0, None, "alçaq", 0),
    ("덥다", 0, None, "isti", 0),
    ("춥다", 0, None, "soyuq", 0),
    ("시원하다", 0, None, "sərin", 0),
    ("따뜻하다", 0, None, "ilıq, mülayim", 0),
    ("싸다", 0, None, "ucuz", 0),
    ("비싸다", 0, None, "bahalı", 0),
    ("켜다", 0, None, "işə salmaq", 0),
    ("끄다", 0, None, "söndürmək", 0),
    ("숙제", 0, None, "ev tapşırığı", 0),
    ("축구", 0, None, "futbol", 0),
    ("농구", 0, None, "basketbol", 0),
    ("예습", 0, None, "dərs hazırlamaq", 0),
    ("복습", 0, None, "təkrar etmək", 0),
    ("사과", 0, None, "alma", 0),
    ("딸기", 0, None, "çiyələk", 0),
    ("빨래", 0, None, "paltar yumaq", 0),
    ("청소", 0, None, "ev yığışdırmaq", 0),
    ("신문", 0, None, "qəzet", 0),
    ("빌리다", 0, None, "borc götürmək (kitab və s.)", 0),
    ("영화관", 0, None, "kinoteatr", 0),
    ("보내다", 0, None, "göndərmək", 0),
    ("돈을 찾다", 0, None, "pul çəkmək (bankdan)", 0),
    ("노래방", 0, None, "karaoke", 0),
    ("수영", 0, None, "üzgüçülük", 0),
    ("쉬다", 0, None, "dincəlmək", 0),
    ("야구", 0, None, "beysbol", 0),
    ("오늘", 0, None, "bugün", 0),
    ("몇", 0, None, "neçə", 0),
    ("월", 0, None, "ay", 0),
    ("며칠", 0, None, "neçənci gün (ayın tarixi mənasında)", 0),
    ("날짜", 0, None, "tarix", 0),
    ("요일", 0, None, "həftənin günü", 0),
    ("평일", 0, None, "həftəiçi", 0),
    ("주말", 0, None, "həftəsonu", 0),
    ("아침", 0, None, "səhər", 0),
    ("일찍", 0, None, "tezdən, erkən", 0),
    ("일어나다", 0, None, "yuxudan durmaq, ayağa qalxmaq", 0),
    ("점심", 0, None, "günorta", 0),
    ("저녁", 0, None, "axşam", 0),
    ("오다", 0, None, "gəlmək", 0),
    ("생일", 0, None, "ad günü", 0),
    ("언제", 0, None, "nə vaxt", 0),
    ("내일", 0, None, "sabah", 0),
    ("중간시험", 0, None, "ara imtahan / midterm exam", 0),
    ("수료식", 0, None, "buraxılış mərasimi", 0),
    ("오전", 0, None, "AM", 0),
    ("마트", 0, None, "market", 0),
    ("과일", 0, None, "meyvə", 0),
    ("채소", 0, None, "tərəvəz", 0),
    ("오후", 0, None, "PM", 0),
    ("기숙사", 0, None, "yataqxana", 0),
    ("모레", 0, None, "birisigün", 0),
    ("수영장", 0, None, "üzgüçülük zalı", 0),
    ("매일", 0, None, "hər gün", 0),
    ("쇼핑", 0, None, "alış-veriş", 0),
    ("산책", 0, None, "gəzinti", 0),
    ("아주", 0, None, "çox", 0),
    ("스포츠센터", 0, None, "idman mərkəzi", 0),
    ("태권도", 0, None, "Taekvondo", 0),
    ("물건", 0, None, "əşya", 0),
    ("같이", 0, None, "birlikdə", 0),
    ("좋아하다", 0, None, "xoşlamaq", 0),
    ("시", 0, None, "saat", 0),
    ("지금 몇 시예요?", 0, None, "şu an saat nədir?", 0),
    ("분", 0, None, "dəqiqə", 0),
    ("하루 일과", 0, None, "günlük rutin", 0),
    ("정각", 0, None, "tam, tamam", 0),
    ("전", 0, None, "əvvəl", 0),
    ("받다", 0, None, "götürmək, qəbul etmək", 0),
    ("자전거", 0, None, "velosiped", 0),
    ("날씨", 0, None, "hava", 0),
    ("수박", 0, None, "qarpız", 0),
    ("복숭아", 0, None, "şaftalı", 0),
    ("키위", 0, None, "kivi", 0),
    ("딸기", 0, None, "çiyələk", 0),
    ("사과", 0, None, "alma", 0),
    ("오렌지", 0, None, "portağal", 0),
    ("잡다", 0, None, "tutmaq", 0),
    ("낮", 0, None, "günorta", 0),
    ("소설책", 0, None, "roman kitabı", 0),
    ("자정", 0, None, "gece saat 12", 0),
    ("정오", 0, None, "gündüz saat 12", 0),
    ("시작하다", 0, None, "başlamaq", 0),
    ("다음 주", 0, None, "gələn həftə", 0),
    ("직원", 0, None, "işçi", 0),
    ("일하다", 0, None, "işləmək", 0),
    ("시험", 0, None, "imtahan", 0),
    ("보다", 0, None, "baxmaq, görmək", 0),
    ("영화를 보다", 0, None, "kinoya baxmaq", 0),
    ("시험을 보다", 0, None, "imtahan vermək", 0),
    ("스키", 0, None, "xizək", 0),
    ("스키를 타다", 0, None, "xizək sürmək", 0),
    ("스케이트", 0, None, "konki", 0),
    ("스케이트를 타다", 0, None, "konki sürmək", 0),
    ("썰매", 0, None, "xizək (sleigh)", 0),
    ("썰매를 타다", 0, None, "xizək sürmək", 0),
    ("당구", 0, None, "bilyard", 0),
    ("...를 치다", 0, None, "...ı vurmaq", 0),
    ("테니스", 0, None, "tenis", 0),
    ("...를 치다", 0, None, "...ı vurmaq", 0),
    ("배드민턴", 0, None, "badminton", 0),
    ("...를 치다", 0, None, "...ı vurmaq", 0),
    ("탁구", 0, None, "stolüstü tenis", 0),
    ("...를 치다", 0, None, "...ı vurmaq", 0),
    ("치다", 0, None, "oynamaq (tenis, badminton və s.)", 0),
    ("주스", 0, None, "meyvə şirəsi", 0),
    ("요리하다", 0, None, "yemək bişirmək", 0),
    ("옷", 0, None, "paltar", 0),
    ("멀다", 0, None, "uzaq", 0),
    ("비싸다", 0, None, "baha", 0),
    ("편하다", 0, None, "rahat", 0),
    ("착하다", 0, None, "saf, səmimi", 0),
    ("조용하다", 0, None, "sakit", 0),
    ("아침 식사", 0, None, "səhər yeməyi", 0),
    ("아침을 먹다", 0, None, "səhər yeməyini yemək", 0),
    ("점심 식사", 0, None, "günorta yeməyi", 0),
    ("점심을 먹다", 0, None, "günorta yeməyini yemək", 0),
    ("저녁 식사", 0, None, "axşam yeməyi", 0),
    ("저녁을 먹다", 0, None, "axşam yeməyini yemək", 0),
    ("yoqa", 0, None, "yoga", 0),
    ("세수하다", 0, None, "əl-üzü yumaq", 0),
    ("하지만", 0, None, "amma, ancaq", 0),
    ("계획하다", 0, None, "planlamaq", 0),
    ("외우다", 0, None, "əzbərləmək", 0),
    ("피곤하다", 0, None, "yorğun olmaq", 0),
    ("휴일", 0, None, "qeyri iş günü", 0),
    ("싫어하다", 0, None, "sevməmək, zəhləsi getmək", 0),
    ("늘", 0, None, "həmişə", 0),
    ("산", 0, None, "dağ", 0),
    ("바쁘다", 0, None, "məşğul olmaq", 0),
    ("기분이 정말 좋습니다.", 0, None, "Kefim həqiqətən yaxşıdır.", 0),
    ("병원", 0, None, "xəstəxana", 0),
    ("밤", 0, None, "gecə", 0),
    ("생각하다", 0, None, "fikirləşmək; düşüncə", 0),
    ("작년", 0, None, "keçən il", 0),
    ("방학", 0, None, "tətil", 0),
    ("산책하다", 0, None, "gəzmək, piyada gəzinti", 0),
    ("음식/ 한국 음식", 0, None, "yemək / Koreya yeməkləri", 0),
    ("좋다", 0, None, "yaxşı", 0),
    ("부산", 0, None, "Koreyanın 2-ci böyük şəhəri", 0),
    ("여행/여행하다", 0, None, "səyahət / səyahət etmək", 0),
    ("어제", 0, None, "dünən", 0),
    ("그저께", 0, None, "sırağagün (dünəndən əvvəlki gün)", 0),
    ("몸", 0, None, "bədən", 0),
    ("아프다", 0, None, "ağrımaq", 0),
    ("결석하다", 0, None, "iştirak etməmək", 0),
    ("찾다", 0, None, "axtarmaq", 0),
    ("신문기자", 0, None, "qəzet jurnalisti", 0),
    ("동생", 0, None, "kiçik bacı/qardaş", 0),
    ("언니", 0, None, "böyük bacı (qızlar üçün )", 0),
    ("운동", 0, None, "idman", 0),
    ("노래하다", 0, None, "mahnı oxumaq", 0),
    ("키 /키가 크다 /작다", 0, None, "boy/hündür boy/alçaq boy", 0),
    ("시인", 0, None, "şair", 0),
    ("한옥", 0, None, "koreya milli evləri", 0),
    ("마을", 0, None, "kənd", 0),
    ("경치", 0, None, "mənzərə", 0),
    ("구경하다", 0, None, "baxmaq, seyr etmək (mənzərə, muzey)", 0),
    ("이야기하다", 0, None, "söhbət emək, danışmaq", 0),
    ("그러면", 0, None, "if that is the case, onda, o zaman", 0),
    ("인사동", 0, None, "Insadong (Seulda gəzməli yer)", 0),
    ("한복", 0, None, "koreya milli geyimi", 0),
    ("입다", 0, None, "gəyinmək", 0),
    ("예쁘다", 0, None, "gözəl", 0),
    ("끄다", 0, None, "söndürmək (işıq, kompyuter, tv)", 0),
    ("비빔밥", 0, None, "koreya yeməyi", 0),
    ("여행하다", 0, None, "səyahət etmək", 0),
    ("만들다", 0, None, "hazırlamaq", 0),
    ("기쁘다", 0, None, "xoşbəxt", 0),
    ("그래서", 0, None, "ona görə də", 0),
    ('배고프다', 0, None, 'ac olmaq', 0),
    ('아프다', 0, None, 'ağrımaq', 0),
    ('약', 0, None, 'dərman', 0),
    ('바쁘다', 0, None, 'məşğul olmaq', 0),
    ('답장', 0, None, 'cavab (məktub, mesaja cvb)', 0),
    ('힘들다', 0, None, 'çətin (əsasən fiziki işlə bağlı işlənir)', 0),
    ('강아지', 0, None, 'küçük', 0),
    ('귀엽다', 0, None, 'sevimli, şirin', 0),
    ('눈', 0, None, '1) göz 2) qar', 0),
    ('한식', 0, None, '한국 음식 /한식당 koreya yeməkləri /koreya restorani', 0),
    ('형', 0, None, 'böyük qardaş (oğlan uşaqları üçün)', 0),
    ('정말', 0, None, 'həqiqətən', 0),
    ('드라마', 0, None, 'serial, drama', 0),
    ('주인공', 0, None, 'baş rol (kino, film)', 0),
    ('다치다', 0, None, 'yaralanmaq', 0),
    ('전통', 0, None, 'milli /전통 문화 -milli mədəniyyət', 0),
    ('박물관', 0, None, '[ 방물관] muzey', 0),
    ('전통', 0, None, 'milli /전통 문화 -milli mədəniyyət', 0),
    ('제주도', 0, None, 'Koreyanın ən böyük adası', 0),
    ('한라산', 0, None, '제주도 - Jeju adasında dağ', 0),
    ('꽃', 0, None, 'gül', 0),
    ('경복궁', 0, None, 'Seulda keçmiş kral saray', 0),
    ('사진을 찍다', 0, None, 'şəkil çəkdirmək', 0),
    ('춘천', 0, None, 'Koreyada şəhər', 0),
    ('닭갈비', 0, None, 'toyuqdan hazırlanan koreya yeməyi', 0),
    ('공기', 0, None, 'hava, atmosfer', 0),
    ('시원하다', 0, None, 'sərin', 0),
    ('경주', 0, None, 'Koreyada tarixi şəhər', 0),
    ('시내', 0, None, 'şəhərin mərkəzi', 0),
    ('누나', 0, None, 'böyük bacı (oğlanlar üçün )', 0),
    ('동생', 0, None, 'kiçik bacı/qardaş', 0),
    ('맑다', 0, None, 'açıq, buludsuz hava', 0),
    ('참', 0, None, '= 정말 həqiqətən də', 0),
    ('차이나타운', 0, None, 'China town', 0),
    ('바람', 0, None, 'külək', 0),
    ('한식당', 0, None, '=한국 식당 koreya restoranı', 0),
    ('불고기', 0, None, 'koreya yeməyi', 0),
    ('정말', 0, None, 'həqiqətən də, çox', 0),
    ('혼자', 0, None, 'təkcə, təkbaşına', 0),
    ('외국 사람', 0, None, '=외국인 xarici, xarici adam', 0),
    ('출발하다', 0, None, 'yola çıxmaq', 0),
    ('경치', 0, None, 'mənzərə', 0),
    ('아름답다', 0, None, '= 예쁘다 gözəl, qəşənq', 0),
    ('무척', 0, None, 'həddən artıq, çox', 0),
    ('도착하다', 0, None, 'çatmaq', 0),
    ('설/설날', 0, None, '[설랄] ay təqvimi ilə Yeni il bayramı', 0),
    ('추석', 0, None, 'Şükran bayramı', 0),
    ('명절', 0, None, 'bayram', 0),
    ('시간', 0, None, 'vaxt', 0),
    ('음력', 0, None, '[음녁] ay təqvimi', 0),
    ('떡국', 0, None, 'Koreya yeməyi (yeni ildə yeyilir)', 0),
    ('윷놀이', 0, None, '[ 윤노리] koreya milli oyunu', 0),
    ('송편', 0, None, 'Koreya şirniyyatı', 0),
    ('성묘', 0, None, 'qəbr ziyarəti', 0),
    ('동물원', 0, None, '동물 zoopark / heyvan', 0),
    ('계절', 0, None, 'fəsil,4fəsil', 0),
    ('봄', 0, None, 'yaz', 0),
    ('여름', 0, None, 'yay', 0),
    ('가을', 0, None, 'payız', 0),
    ('겨울', 0, None, 'qış', 0),
    ('춥다', 0, None, 'soyuq', 0),
    ('덥다', 0, None, 'isti', 0),
    ('따뜻하다', 0, None, '/시원하다 mülayim / sərin', 0),
    ('항상/늘', 0, None, 'həmişə', 0),
    ('아름답다', 0, None, '/ 예쁘다 gözəl', 0),
    ('산/ 등산', 0, None, 'dağ / dağaçıxma', 0),
    ('화장하다', 0, None, 'makyaj etmək', 0),
    ('맵다', 0, None, 'acılı', 0),
    ('무겁다', 0, None, 'ağır', 0),
    ('돕다', 0, None, 'kömək etmək', 0),
    ('백화점', 0, None, 'univermaq', 0),
    ('구두', 0, None, 'ayaqqabı', 0),
    ('남자 친구', 0, None, '/여자 친구 boyfriend/girlfriend', 0),
    ('질문하다', 0, None, 'sual vermək', 0),
    ('요즘', 0, None, 'bugünlərdə, son günlərdə', 0),
    ('자주', 0, None, 'tez-tez', 0),
    ('눈이 오다', 0, None, '/ 내리다 qar yağmaq', 0),
    ('비가 오다', 0, None, '/내리다 yağış yağmaq', 0),
    ('맑다', 0, None, '/흐리다 açıq/ tutqun', 0),
    ('바람이 불다', 0, None, 'külək əsmək', 0),
    ('자주', 0, None, 'tez-tez', 0),
    ('지난 겨울', 0, None, 'keçən qış', 0),
    ('지하철역', 0, None, 'metro stansiyası', 0),
    ('바다', 0, None, 'dəniz', 0),
    ('단풍', 0, None, 'xəzan', 0),
    ('모자', 0, None, 'papaq', 0),
    ('스노보드', 0, None, 'snow board', 0),
    ('눈썰매', 0, None, 'kirşə, xizək (oturub sürülən)- sleigh/…를 타다', 0),
    ('눈사람', 0, None, 'qaradamı', 0),
    ('눈싸움', 0, None, '/눈싸움을 하다 qartopu oynamaq', 0),
    ('스키장', 0, None, 'xizək kurortu', 0),
    ('해수욕장', 0, None, 'çimərlik', 0),
    ('계곡', 0, None, 'vadi', 0),
    ('극장', 0, None, 'teatr', 0),
    ('공항', 0, None, 'aeroport', 0),
    ('노래방', 0, None, 'karaoke', 0),
    ('흐리다', 0, None, 'tutqun', 0),
    ('시장', 0, None, 'bazar', 0),
    ('회', 0, None, 'çiy balıq yeməyi', 0),
    ('무척', 0, None, 'həddən artıq', 0),
    ('설악산', 0, None, 'Koreyada dağ (Soraq dağı)', 0),
    ('또', 0, None, '/ 또 만나요 yenidən, təkrar / görüşənədək, yenə görüşərik', 0),
    ('요즘', 0, None, 'bugünlərdə, son günlərdə', 0),
    ('막국수', 0, None, 'makaronlu yemək adı', 0),
    ('올해', 0, None, 'bu il', 0),
    ('조금', 0, None, 'biraz', 0),
    ('꽃구경', 0, None, 'güllərə baxmaq', 0),
    ('야외', 0, None, 'açıq hava, çöl, bayır', 0),
    ('피다', 0, None, 'açmaq(gül)', 0),
    ('특히', 0, None, 'xüsusilə', 0),
    ('벚꽃', 0, None, 'sakura çiçəkləri', 0),
    ('여의도', 0, None, 'seulda yer adı', 0),
    ('축제', 0, None, 'festival', 0),
    ('해수욕장', 0, None, 'çimərlik', 0),
    ('강원도', 0, None, 'Əyalətin adı', 0),
    ('속초', 0, None, 'Şəhər adı', 0),
    ('해운대', 0, None, 'Busanda çimərlik', 0),
    ('지리산', 0, None, 'dağ adı', 0),
    ('눈', 0, None, 'Qar;göz', 0),
    ('계획', 0, None, 'plan', 0),
    ('외우다', 0, None, 'əzbərləmək', 0),
    ('꼭', 0, None, 'mütləq', 0),
    ('입학하다', 0, None, '(tələffüzü이파카다) qəbul olmaq (məktəb, uni)', 0),
    ('놀다', 0, None, 'oynamaq, əylənmək', 0),
    ('중간 시험', 0, None, 'mid-term exam', 0),
    ('기말 시험', 0, None, 'final-term exam', 0),
    ('문화 수업', 0, None, 'mədəniyyət dərsi', 0),
    ('시험을 보다', 0, None, 'imtahan vermək', 0),
    ('시험에 붙다', 0, None, 'keçmək(imtahan)/kəsilmək', 0),
    ('합격하다', 0, None, 'keçmək(imtahan)/kəsilmək', 0),
    ('샤워하다', 0, None, 'duş almaq', 0),
    ('창문', 0, None, 'pəncərə', 0),
    ('초대하다', 0, None, 'dəvət etmək', 0),
    ('얼마', 0, None, 'nə qədər müddət', 0),
    ('하루', 0, None, 'gün, bir gün', 0),
    ('이틀', 0, None, 'iki gün', 0),
    ('사흘', 0, None, '3 gün', 0),
    ('나흘', 0, None, '4 gün', 0),
    ('닷새', 0, None, '5gün', 0),
    ('엿새', 0, None, '6gün', 0),
    ('이레', 0, None, '7 gün', 0),
    ('열흘', 0, None, '10 gün', 0),
    ('돌아가다', 0, None, 'qayıtmaq', 0),
    ('손', 0, None, 'əl', 0),
    ('씻다', 0, None, 'yumaq', 0),
    ('이 , 이빨', 0, None, 'diş', 0),
    ('닦다', 0, None, 'fırçalamaq, təmizləmək', 0),
    ('샤워', 0, None, 'duş', 0),
    ('보통', 0, None, 'adətən', 0),
    ('벗다', 0, None, 'soyunmaq', 0),
    ('빗다', 0, None, 'daramaq / daraq', 0),
    ('식사', 0, None, 'yemək', 0),
    ('조금 전에', 0, None, 'biraz əvvəl', 0),
    ('잠시 후에', 0, None, 'birazdan', 0),
    ('마치다', 0, None, 'bitirmək', 0),
    ('비행기', 0, None, 'təyyarə', 0),
    ('학기', 0, None, 'semestr', 0),
    ('새', 0, None, 'təzə / quş', 0),
    ('어휘', 0, None, 'söz', 0),
    ('아르바이트', 0, None, 'part-time iş', 0),
    ('유학생', 0, None, 'xaricdə oxuyan tələbə, beynəlxalq tələbə', 0),
    ("모음", 0, None, "yığıncaq", 0),
    ("비행기", 0, None, "təyyarə", 0),
    ("표", 0, None, "bilet", 0),
    ("예매하다", 0, None, "to book, əvvəlcədən almaq", 0),
    ("친척", 0, None, "qohum", 0),
    ("돌아오다", 0, None, "Qayıdıb gəlmək", 0),
    ("경기", 0, None, "yarış", 0),
    ("여러 가지", 0, None, "müxtəlif", 0),
    ("음료수", 0, None, "içki", 0),
    ("간식", 0, None, "snack, atışdırmalıq yüngül yemək", 0),
    ("농구장", 0, None, "basketbol meydançası", 0),
    ("새해", 0, None, "yeni il (new year)", 0),
    ("계획", 0, None, "plan", 0),
    ("세우다", 0, None, "qurmaq, yaratmaq", 0),
    ("담배", 0, None, "siqaret", 0),
    ("끊다", 0, None, "kəsmək, tərgitmək", 0),
    ("벌다", 0, None, "pul qazanmaq", 0),
    ("결혼/결혼하다", 0, None, "toy /evlənmək", 0),
    ("노력하다", 0, None, "Cəhd etmək, əlindən gələni etmək", 0)]

swapped_vocab_list = [(t[3], t[1], t[2], t[0], t[4]) for t in vocab_list]
print(len(swapped_vocab_list))
